import type { Dependency, EventEnvelope, Resource, Snapshot, Task } from "../domain/types";
import { checksum } from "../utils";
import { detectDependencyCycle } from "../algorithms/graph";
export interface ValidationError { path:string; code:string; message:string; }
export type ValidationResult<T> = { success:true; data:T } | { success:false; errors:ValidationError[] };
export interface BranchDefinition { id:string; sourceBranchId?:string; baseSequence?:number; }
export interface ChronicleOpsFile { schemaVersion:string; exportedAt:string; workspaceId:string; activeBranchId:string; branches:BranchDefinition[]; events:EventEnvelope[]; snapshots:Snapshot[]; settings:{simulationSpeed:number;showCriticalPath:boolean;showSlack:boolean}; }
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
const int = (value: unknown, min = 0, max = Number.MAX_SAFE_INTEGER) => Number.isInteger(value) && Number(value) >= min && Number(value) <= max;
export function validateChronicleOpsFile(input: unknown): ValidationResult<ChronicleOpsFile> {
 const errors:ValidationError[]=[]; const add=(path:string,code:string,message:string)=>errors.push({path,code,message}); if(!object(input)){add("$","TYPE","Expected object");return{success:false,errors};} const x=input;
 if(x.schemaVersion!=="1.0")add("schemaVersion","VERSION","Expected compatible schema 1.0"); if(typeof x.workspaceId!=="string"||!x.workspaceId)add("workspaceId","TYPE","Expected workspace id"); if(!Array.isArray(x.branches)||!x.branches.length)add("branches","TYPE","Expected non-empty branches array"); if(!Array.isArray(x.events)||!x.events.length)add("events","TYPE","Expected non-empty events array"); if(!Array.isArray(x.snapshots))add("snapshots","TYPE","Expected snapshots array"); if(!object(x.settings)||!int(x.settings.simulationSpeed,1)||typeof x.settings.showCriticalPath!=="boolean"||typeof x.settings.showSlack!=="boolean")add("settings","TYPE","Invalid settings");
 const branchIds=new Set<string>(); if(Array.isArray(x.branches))x.branches.forEach((branch,i)=>{if(!object(branch)||typeof branch.id!=="string"||!branch.id)add(`branches[${i}]`,`TYPE`,`Invalid branch`);else if(branchIds.has(branch.id))add(`branches[${i}].id`,`UNIQUE`,`Duplicate branch id`);else branchIds.add(branch.id);});
 const eventIds=new Set<string>(), commandIds=new Set<string>(), byBranch=new Map<string,EventEnvelope[]>(); if(Array.isArray(x.events))x.events.forEach((raw,i)=>{if(!object(raw)){add(`events[${i}]`,`TYPE`,`Expected event object`);return;} const event=raw as unknown as EventEnvelope;if(typeof event.eventId!=="string"||eventIds.has(event.eventId))add(`events[${i}].eventId`,`UNIQUE`,`Event id must be unique`);eventIds.add(event.eventId);if(typeof event.commandId!=="string"||!event.commandId||commandIds.has(event.commandId))add(`events[${i}].commandId`,`UNIQUE`,`Command id must be unique`);commandIds.add(event.commandId);if(!int(event.sequence))add(`events[${i}].sequence`,`INTEGER`,`Sequence must be non-negative integer`);if(typeof event.branchId!=="string"||!branchIds.has(event.branchId))add(`events[${i}].branchId`,`REFERENCE`,`Unknown branch`);if(typeof event.type!=="string"||!object(event.payload))add(`events[${i}]`,`PAYLOAD`,`Invalid event payload`);const list=byBranch.get(event.branchId)??[];list.push(event);byBranch.set(event.branchId,list);});
 byBranch.forEach((events,branch)=>events.sort((a,b)=>a.sequence-b.sequence).forEach((event,index)=>{if(index&&event.sequence<=events[index-1].sequence)add(`events.${branch}[${index}].sequence`,`ORDER`,`Sequence must strictly increase`);}));
 const tasks=new Map<string,Task>(),resources=new Map<string,Resource>(),dependencies:Dependency[]=[]; for(const event of (Array.isArray(x.events) ? x.events : []) as EventEnvelope[]){const p=event.payload as Record<string,unknown>;if(event.type==="TaskCreated"&&object(p.task)){const task=p.task as unknown as Task;if(tasks.has(task.id))add("task.id","UNIQUE","Duplicate task id");tasks.set(task.id,task);if(!int(task.durationDays,1,30))add(`task.${task.id}.durationDays`,`RANGE`,`Duration must be 1-30`);if(!int(task.remainingDays))add(`task.${task.id}.remainingDays`,`RANGE`,`Remaining days must be non-negative`);if(!int(task.progress,0,100))add(`task.${task.id}.progress`,`RANGE`,`Progress must be 0-100`);if(!int(task.priority,1,5))add(`task.${task.id}.priority`,`RANGE`,`Priority must be 1-5`);if((task.status==="completed")!== (task.completedDay!==null))add(`task.${task.id}.completedDay`,`CONSISTENCY`,`Completed status and completedDay must agree`);}if(event.type==="ResourceCreated"&&object(p.resource)){const r=p.resource as unknown as Resource;resources.set(r.id,r);if(!int(r.capacityPerDay,1,4)||!Array.isArray(r.skills)||!r.skills.length)add(`resource.${r.id}`,`RANGE`,`Invalid resource`);if(!Array.isArray(r.unavailableDays)||new Set(r.unavailableDays).size!==r.unavailableDays.length||r.unavailableDays.some(day=>!int(day)))add(`resource.${r.id}.unavailableDays`,`RANGE`,`Unavailable days must be unique non-negative integers`);}if(event.type==="DependencyAdded"&&object(p.dependency))dependencies.push(p.dependency as unknown as Dependency);}
 dependencies.forEach((d,i)=>{if(!tasks.has(d.predecessorTaskId)||!tasks.has(d.successorTaskId))add(`dependencies[${i}]`,`REFERENCE`,`Dependency task missing`);if(d.predecessorTaskId===d.successorTaskId)add(`dependencies[${i}]`,`SELF`,`Dependency cannot reference itself`);}); const cycle=detectDependencyCycle([...tasks.keys()],dependencies);if(cycle)add("dependencies","CYCLE",cycle.join(" -> ")); if(Array.isArray(x.snapshots))x.snapshots.forEach((snapshot,i)=>{if(!object(snapshot)||!int(snapshot.sequence)||!object(snapshot.state)||typeof snapshot.checksum!=="string"||snapshot.checksum!==checksum(snapshot.state))add(`snapshots[${i}]`,`CHECKSUM`,`Invalid snapshot`);});
 return errors.length?{success:false,errors}:{success:true,data:x as unknown as ChronicleOpsFile};
}
