import type { EventEnvelope } from "../domain/types";
import { clone } from "../utils";
export type AppendResult={success:true;newVersion:number;appendedEventIds:string[]}|{success:false;error:{code:"VERSION_CONFLICT";expectedVersion:number;actualVersion:number}};
export interface EventStore { append(events:EventEnvelope[],expectedVersion:number):AppendResult; readBranch(branchId:string,fromSequence?:number):EventEnvelope[];getVersion(branchId:string):number;createBranch(sourceBranchId:string,atSequence:number,newBranchId:string):{success:boolean;error?:string}; }
export function createInMemoryEventStore():EventStore {
 const branches=new Map<string,EventEnvelope[]>(); const commandResults=new Map<string,AppendResult>();
 const events=(branchId:string)=>branches.get(branchId)??[];
 return { append(incoming,expectedVersion) { const cached=commandResults.get(incoming[0]?.commandId??"");if(cached)return clone(cached);const branchId=incoming[0]?.branchId??"main";const current=events(branchId);const actual=current.length?current[current.length-1].sequence:0;if(expectedVersion!==actual)return {success:false,error:{code:"VERSION_CONFLICT",expectedVersion,actualVersion:actual}};if(!incoming.length||incoming.some((event,index)=>event.sequence!==actual+index+1)||incoming.some(event=>current.some(existing=>existing.eventId===event.eventId)))throw new Error("Invalid atomic event batch");const copied=incoming.map(e=>Object.freeze(clone(e)) as EventEnvelope);branches.set(branchId,[...current,...copied]);const result:AppendResult={success:true,newVersion:copied.length?copied[copied.length-1].sequence:actual,appendedEventIds:copied.map(e=>e.eventId)};if(incoming[0])commandResults.set(incoming[0].commandId,result);return clone(result); }, readBranch(branchId,from=0){return clone(events(branchId).filter(e=>e.sequence>=from));},getVersion(branchId){const es=events(branchId);return es.length?es[es.length-1].sequence:0;},createBranch(source,at,newId){if(branches.has(newId))return{success:false,error:"BRANCH_EXISTS"};const sourceEvents=events(source).filter(e=>e.sequence<=at);if(sourceEvents.length!==at&&at!==0)return{success:false,error:"SEQUENCE_NOT_FOUND"};branches.set(newId,sourceEvents.map(e=>({...clone(e),branchId:newId})));return{success:true};} };
}
